name: Swift CI Workflow

on:
  push:
    branches: [ "main", "dev", "qa" ]
  pull_request:
    branches: [ "main", "dev", "qa", "feature/*", "release/*" ]

env:
  XCODE_VERSION: '16.1'
  PROJECT_NAME: 'lint-test-ios'
  SCHEME_NAME: 'lint-test-ios'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
          
      - name: List available simulators
        run: xcrun simctl list devices available
        
      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ matrix.configuration }}-${{ hashFiles('**/*.xcodeproj') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-${{ matrix.configuration }}-
            ${{ runner.os }}-derived-data-
            
      - name: Build for iOS Simulator
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -configuration ${{ matrix.configuration }} \
            -destination "platform=iOS Simulator,name=Any iOS Simulator Device" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty
