name: ci workflow

on: 
 push:
  branches: [main, master]
   

env: 
 PROJECT_NAME: lint-test-ios
 XCODE_VERSION: '16.1'

jobs:
 lint:
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: set up xcode
     uses: maxim-lobanov/setup-xcode@v1
     with:
      xcode_version: ${{env.XCODE_VERSION}}

   - name: install swiftlint
     run: brew install swiftlint

   - name: run swiftlint
     run: swiftlint lint --reporter github-actions-logging

 build:
   needs: lint
   runs-on: macos-latest

   steps:
    - name: checkout the code
      uses: actions/checkout@v4

    - name: set up xcode 
      uses: maxim-lobanov/setup-xcode@v1
      with:
       xcode_verson: ${{env.XCODE_VERSION}}

    - name: build swift code
      run: swift build
